server:
  port: 8082

spring:
  application:
    name: estoque-service

  datasource:
    url: jdbc:h2:mem:estoquedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  artemis:
    mode: embedded
    embedded:
      enabled: true

# Cliente Feign para buscar Produtos
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# Resiliência no Feign
resilience4j:
  circuitbreaker:
    instances:
      produtoService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        wait-duration-in-open-state: 15s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    br.edu.inventory: DEBUG
